language: scala

dist: trusty

sudo: required

jdk:
  - oraclejdk8

scala:
  - 2.12.6

addons:
  postgresql: "9.5"

before_script:
  - psql -c 'create database gem' -U postgres

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 9.4.0
  - nvm use 9.4.0
  - npm install jsdom
  - pip install --user awscli
script:
  - sbt -jvm-opts travis-jvmopts -Docs3.skipDependencyUpdates headerCheck test:headerCheck scalastyle sql/flywayMigrate
  - sbt -jvm-opts travis-jvmopts -Docs3.skipDependencyUpdates compile test:compile
  - sbt -jvm-opts travis-jvmopts -Docs3.skipDependencyUpdates test
  - sbt -jvm-opts travis-jvmopts -Docs3.skipDependencyUpdates ui/fastOptJS
  - sbt -jvm-opts travis-jvmopts -Docs3.skipDependencyUpdates seqexec_web_client/fastOptJS::webpack

after_script:
  - $TRAVIS_BUILD_DIR/build/weigh.sh

cache:
  directories:
  - $HOME/.sbt/1.0
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
  - $HOME/.nvm
  - $HOME/.rvm/
  - vendor/bundle

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -type f -delete
